# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160928_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavmusic',
            name='music',
        ),
        migrations.RemoveField(
            model_name='userfavmusic',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='musics',
            field=models.ManyToManyField(to='api.Music'),
        ),
        migrations.DeleteModel(
            name='UserFavMusic',
        ),
    ]
