# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160929_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='musics',
            field=models.ManyToManyField(blank=True, to='api.Music'),
        ),
    ]
